openapi: "3.0.0"
info:
  description: 'HiCotech api doc.'
  version: "0.1.0"
  title: HiCotech API 2021

servers:
  - url: 'http://127.0.0.1:5000/api'


components:
  securitySchemes:
    Token: # TODO this isn't sending in swagger-ui??
      type: http
      description: Bearer Token
      scheme: Bearer
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        dateOfBirth:
          type: string
        city:
          type: string
        weight:
          type: integer
        subscription:
          type: string
        sexe:
          type: string
        role:
          type: string
            
  
        
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
                       
security:
  -  Token: [] # Require token for all requests (unless otherwise specified)
tags:
  - name: user
    description: Operations about User

paths:
  /users:
    get:
      tags:
        - user
      summary: Get All Users 
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            additionalProperties:
              type: integer
              format: int32 
    post:
      tags:
        - user
      summary: Add a new User 
      requestBody:
        content:
          application/json:    # Media type
            schema:            # Request body contents
              $ref: '#/components/schemas/User'   # Reference to an object
      responses:
        '200':
          description: OK
  /login: 
    post:
      tags:
        - user
      summary: Login   User 
      requestBody:
        content:
          application/json:    # Media type
            schema:            # Request body contents
              $ref: '#/components/schemas/UserLogin'   # Reference to an object
      responses:
        '200':
          description: OK

  /users/{Id}:
    get:
      tags:
        - user
      summary: Returns a user by ID. 
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type : string
      responses: 
        '200':
          description: OK
    put:
      tags:
        - user
      summary: Update a user by ID.
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type : string

      requestBody:
        content:
          application/json:    # Media type
            schema:            # Request body contents
              $ref: '#/components/schemas/User'   
      responses: 
        '200':
          description: OK
    delete:
      tags:
        - user
      summary: Delete a user by ID.
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type : string
           
      responses: 
        '200':
          description: OK
  